### PR TITLE
chore: fix typo in codec_frugal

### PR DESCRIPTION
**Pull request by fujie-xiyou**
#### What this PR does / why we need it (en: English/zh: Chinese):

en: Unified use of `codec` naming
zh: 统一使用`codec`命名

### CODE REVIEW

**Comment by rogerogers** [comment]
cla please.

**Comment by rogerogers** [comment]
ci: Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
docs: Documentation only changes
feat: A new feature
optimize: A new optimization
fix: A bug fix
perf: A code change that improves performance
refactor: A code change that neither fixes a bug nor adds a feature
style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
test: Adding missing tests or correcting existing tests
chore: Changes to the build process or auxiliary tools and libraries such as documentation generation

这个应该是docs或者chore

**Comment by fujie-xiyou** [comment]
@rogerogers done

**Comment by rogerogers** [comment]
> @rogerogers done

https://github.com/cloudwego/cloudwego.github.io/blob/main/content/en/docs/kitex/Tutorials/advanced-feature/codec_frugal.md?plain=1
英文的我看也是这样，方便一起改下吗😂，两边保持一致

**Comment by GuangmingLuo** [comment]
title -> chore: fix typo in codec_frugal

**Comment by GuangmingLuo** [comment]
@fujie-xiyou would you mind  updating the English version as well ?

**Comment by fujie-xiyou** [comment]
> > @rogerogers done
> 
> https://github.com/cloudwego/cloudwego.github.io/blob/main/content/en/docs/kitex/Tutorials/advanced-feature/codec_frugal.md?plain=1 英文的我看也是这样，方便一起改下吗😂，两边保持一致

done @rogerogers @GuangmingLuo

**Review by GuangmingLuo — APPROVED** [review]

**Pull request merged**
